---
name: XML-Descent
version: 1.02
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Recursive descent XML parsing
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=XML-Descent
  license: http://dev.perl.org/licenses/
  repository: https://svn.hexten.net/andy/Perl/XML-Descent/trunk
requires:
  Test::Differences: 0
  Test::More: 0
  XML::TokeParser: 0
provides:
  XML::Descent:
    file: lib/XML/Descent.pm
    version: 1.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
