--- #YAML:1.0
name:                XML-Descent
version:             v0.0.3
abstract:            Recursive descent XML parsing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Std:                    0
    Test::More:                    0
    version:                       0
    XML::TokeParser:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
