--- #YAML:1.0
name:                XML-Descent
version:             0.10
abstract:            Recursive descent XML parsing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Test::More:                    0
    XML::TokeParser:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
